import React, { useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { FaRobot, FaMap, FaCalendarCheck, FaArrowRight, FaCheckCircle } from "react-icons/fa";
import { useAuth } from "../contexts/AuthContext";

const Home = () => {
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();

  useEffect(() => {
    if (isAuthenticated) {
      navigate("/dashboard");
    }
  }, [isAuthenticated, navigate]);

  const features = [
    {
      icon: FaRobot,
      title: "AI-Powered Planning",
      description:
        "Personalized itineraries generated by advanced AI, tailored to your preferences and travel style.",
    },
    {
      icon: FaMap,
      title: "Interactive Maps",
      description:
        "Explore destinations with interactive maps and location guides to discover hidden gems.",
    },
    {
      icon: FaCalendarCheck,
      title: "Trip Management",
      description:
        "Organize and manage all your trips in one place with easy access and real-time updates.",
    },
  ];

  const benefits = [
    "Smart AI recommendations",
    "Real-time trip updates",
    "Collaborative planning",
    "Budget tracking",
  ];

  return (
    <div className="min-h-screen bg-bg relative">
      <div className="absolute inset-0 bg-grid-pattern bg-grid opacity-40 pointer-events-none" />

      <section className="relative py-16 lg:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl">
            <motion.p
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              className="section-label mb-4"
            >
              Intelligent Travel
            </motion.p>

            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="text-4xl md:text-6xl lg:text-7xl font-display font-bold text-text-primary leading-[1.1] mb-6"
            >
              Plan your perfect trip with{" "}
              <span className="text-accent">precision</span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.15 }}
              className="text-base md:text-xl text-text-secondary mb-10 max-w-2xl leading-relaxed"
            >
              Discover the world with intelligent travel planning. Personalized
              itineraries, interactive maps, and seamless trip management.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="flex flex-col sm:flex-row gap-3"
            >
              <Link
                to="/register"
                className="group inline-flex items-center justify-center px-6 py-3.5 bg-accent text-bg font-semibold rounded-md hover:brightness-110 transition-all shadow-glow min-h-[44px]"
              >
                Get Started Free
                <FaArrowRight className="ml-2 group-hover:translate-x-1 transition-transform" />
              </Link>
              <Link
                to="/login"
                className="inline-flex items-center justify-center px-6 py-3.5 border border-border text-text-primary font-medium rounded-md hover:bg-accent-muted hover:border-accent/30 transition-all min-h-[44px]"
              >
                Sign In
              </Link>
            </motion.div>

            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.5 }}
              className="hidden md:flex mt-12 flex-wrap gap-3"
            >
              {benefits.map((benefit, index) => (
                <div
                  key={index}
                  className="flex items-center text-sm text-text-secondary bg-surface-elevated border border-border px-4 py-2 rounded-full"
                >
                  <FaCheckCircle className="text-success mr-2 flex-shrink-0 h-3.5 w-3.5" />
                  {benefit}
                </div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      <section className="relative py-16 lg:py-24 border-t border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12"
          >
            <p className="section-label mb-3">Capabilities</p>
            <h2 className="text-3xl md:text-4xl font-display font-bold text-text-primary">
              Why TripSathi
            </h2>
          </motion.div>

          <div className="space-y-4">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="group flex flex-col md:flex-row md:items-center gap-4 md:gap-8 p-6 rounded-lg border border-border bg-surface hover:border-accent/20 hover:bg-accent-muted/30 transition-all duration-300"
              >
                <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-accent-muted border border-accent/20 flex-shrink-0">
                  <feature.icon className="h-5 w-5 text-accent" />
                </div>
                <div className="flex-1">
                  <h3 className="text-lg font-display font-semibold text-text-primary mb-1">
                    {feature.title}
                  </h3>
                  <p className="text-sm text-text-secondary leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="relative py-16 lg:py-24 border-t border-border">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.98 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="surface-card-elevated p-10 md:p-14"
          >
            <h2 className="text-2xl md:text-4xl font-display font-bold text-text-primary mb-4">
              Ready to start your journey?
            </h2>
            <p className="text-text-secondary mb-8">
              Join travelers who trust TripSathi for their adventures.
            </p>
            <Link
              to="/register"
              className="inline-flex items-center justify-center px-8 py-3.5 bg-accent text-bg font-semibold rounded-md hover:brightness-110 transition-all shadow-glow min-h-[44px]"
            >
              Create Your Free Account
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default Home;
